"""
SQL Agent creation and configuration.

Wraps LangChain's SQLDatabaseToolkit and create_sql_agent
into a reusable factory function with CRUD-aware prompting and robust error recovery.
"""

import re
from langchain_groq import ChatGroq
from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.agent_toolkits.sql.base import create_sql_agent
from langchain.agents.agent_types import AgentType


# ─── CRUD-Aware Agent Prefix ───
AGENT_PREFIX = """You are an AI database assistant designed to interact with a SQL database.
You can perform ALL of the following operations using {dialect} syntax:

• SELECT — Query and retrieve data
• INSERT — Add new records
• UPDATE — Modify existing records
• DELETE — Remove records

WHEN THE USER ASKS YOU TO:
- "add", "insert", "create", "register", "enroll" → Generate INSERT SQL statement
- "update", "modify", "change", "set", "edit" → Generate UPDATE SQL statement with WHERE clause
- "delete", "remove", "drop record" → Generate DELETE SQL statement with WHERE clause
- "show", "list", "find", "get", "how many", "count", "average", "highest", "top" → Generate SELECT SQL statement

ANALYTICAL GUIDANCE:
- For "top performers" or "highest X": Use ORDER BY column DESC LIMIT N.
- For "average X" or "maximum Y": Use AVG(column), MAX(column), MIN(column).
- For "missing values": Inspect columns and return counts of NULL values per column.
- For "duplicate records": Identify rows with identical non-primary key values.

IMPORTANT RULES:
1. Always inspect the table schema using the provided tools before generating SQL.
2. For INSERT: Match column names and data types exactly.
3. For UPDATE: ALWAYS include a WHERE clause targeting specific records (e.g. UPDATE table SET col = new_val WHERE name = 'target').
4. For DELETE: ALWAYS include a WHERE clause targeting specific records.
5. Provide the generated SQL in a ```sql ... ``` code block.
6. Unless the user specifies a count, limit SELECT results to at most {top_k} rows.
7. Never generate DROP TABLE, DROP DATABASE, or TRUNCATE statements.
8. Always use correct SQL syntax for {dialect}.

CRITICAL RESPONSE FORMAT INSTRUCTION:
When you finish your reasoning and are ready to provide an answer or SQL query to the user, you MUST start your final response line with "Final Answer: ".
Example format:
Final Answer: The requested row can be removed with the following SQL statement:
```sql
DELETE FROM table_name WHERE condition;
```"""


def custom_handle_parsing_error(error: Exception) -> str:
    """Custom error recovery handler for AgentExecutor output parsing errors.

    Extracts raw text generated by LLM when it fails to prefix with 'Final Answer:',
    enabling the agent to gracefully return the response without raising an exception.
    """
    err_text = str(error)
    clean_err = re.sub(r"\s*For troubleshooting, visit:.*$", "", err_text, flags=re.DOTALL)
    raw_text = re.sub(r"^.*?Could not parse LLM output:\s*[`'\"]*", "", clean_err, flags=re.DOTALL)
    raw_text = re.sub(r"[`'\"]*$", "", raw_text, flags=re.DOTALL).strip()
    if raw_text:
        return f"Final Answer: {raw_text}"
    return "Final Answer: The requested database operation has been processed."


def create_sql_agent_instance(db: SQLDatabase, llm: ChatGroq):
    """Create and return a CRUD-capable LangChain SQL agent.

    Uses a custom prefix and custom output parser error handler to prevent
    ValueError crashes when models output un-prefixed natural language responses.
    """
    toolkit = SQLDatabaseToolkit(db=db, llm=llm)
    agent = create_sql_agent(
        llm=llm,
        toolkit=toolkit,
        verbose=True,
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        prefix=AGENT_PREFIX,
        handle_parsing_errors=custom_handle_parsing_error,
        max_iterations=10,
    )
    agent.handle_parsing_errors = custom_handle_parsing_error
    return agent
