"""
PDF Export Utility.

Converts DataFrames to formatted PDF document bytes using fpdf2.
"""

import io
import pandas as pd
from fpdf import FPDF
from utils.logger import setup_logger

logger = setup_logger(__name__)


class PDFReport(FPDF):
    """Custom FPDF layout with header and footer."""

    def __init__(self, title_text: str = "Database Report"):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.title_text = title_text

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, self.title_text, border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 5, "Generated by AI Database Assistant", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def export_to_pdf(df: pd.DataFrame, title: str = "Database Export Report") -> bytes:
    """Convert DataFrame to formatted PDF document bytes.

    Args:
        df: Input pandas DataFrame.
        title: Report title string.

    Returns:
        PDF file bytes.
    """
    if df is None or df.empty:
        return b""

    try:
        pdf = PDFReport(title_text=title)
        pdf.alias_nb_pages()
        pdf.add_page()

        pdf.set_font("Helvetica", "B", 9)

        cols = list(df.columns)
        num_cols = len(cols)
        page_width = 277  # A4 landscape printable width in mm
        col_width = max(20, min(60, page_width / num_cols))

        # Header Row
        pdf.set_fill_color(30, 41, 59)
        pdf.set_text_color(255, 255, 255)
        for col in cols:
            val_str = str(col)[:15]
            pdf.cell(col_width, 8, val_str, border=1, align="C", fill=True)
        pdf.ln()

        # Data Rows
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(0, 0, 0)
        fill = False

        for _, row in df.iterrows():
            pdf.set_fill_color(241, 245, 249) if fill else pdf.set_fill_color(255, 255, 255)
            for col in cols:
                cell_val = str(row[col]) if row[col] is not None else "—"
                cell_val = cell_val[:18]
                pdf.cell(col_width, 7, cell_val, border=1, align="L", fill=True)
            pdf.ln()
            fill = not fill

        return bytes(pdf.output())
    except Exception as e:
        logger.error("PDF export failed: %s", e)
        return b""
